# Generated by Django 3.2.9 on 2022-01-30 09:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('semsec', models.CharField(default='5A', max_length=2, primary_key=True, serialize=False)),
                ('semester', models.IntegerField(default='5', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)])),
                ('section', models.CharField(default='A', max_length=1)),
            ],
            options={
                'db_table': 'Class',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('d_id', models.CharField(choices=[('CS', 'CS'), ('IS', 'IS'), ('ECE', 'ECE'), ('IEM', 'IEM'), ('CIV', 'CIV'), ('MECH', 'MECH'), ('EEE', 'EEE')], max_length=100, primary_key=True, serialize=False)),
                ('d_name', models.CharField(choices=[('Computer Science And Engineering', 'Computer Science And Engineering'), ('Information Sciecne And Engineering', 'Information Sciecne And Engineering'), ('Electronics And Communication', 'Electronics And Communication'), ('Industrial Engineering And Management', 'Industrial Engineering And Management'), ('Civil Engineering', 'Civil Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electronics And Electrical Engineering', 'Electronics And Electrical Engineering')], max_length=100)),
            ],
            options={
                'db_table': 'DEPARTMENT',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('password', models.CharField(default='0000', max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmapp.department')),
            ],
            options={
                'db_table': 'TEACHER',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('password', models.CharField(default='0000', max_length=100)),
                ('branch', models.ForeignKey(default='CS', on_delete=django.db.models.deletion.CASCADE, to='pmapp.department')),
                ('semsec', models.ForeignKey(default='5A', on_delete=django.db.models.deletion.CASCADE, to='pmapp.classsection')),
            ],
            options={
                'db_table': 'STUDENT',
            },
        ),
    ]
