# Generated by Django 3.2.9 on 2022-01-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subj_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('subj_name', models.CharField(max_length=100)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1)),
                ('credits', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
            ],
            options={
                'db_table': 'SUBJECT',
            },
        ),
    ]
