# Generated by Django 3.2.9 on 2022-01-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0002_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassSection',
            new_name='Class_Section',
        ),
    ]
