# Generated by Django 3.2.9 on 2022-01-30 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0003_rename_classsection_class_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='branch',
            field=models.ForeignKey(default='CS', on_delete=django.db.models.deletion.CASCADE, to='pmapp.department'),
        ),
    ]
