# Generated by Django 3.2.9 on 2022-01-30 19:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0004_subject_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateField(auto_now=True, null=True)),
                ('deadline', models.DateField()),
                ('submisstion_date', models.DateField(auto_now=True, null=True)),
                ('project_title', models.CharField(blank=True, max_length=100, null=True)),
                ('source_url', models.URLField(blank=True, max_length=400, null=True)),
                ('grade', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('assigned_by', models.ForeignKey(default='CS100', on_delete=django.db.models.deletion.CASCADE, to='pmapp.teacher')),
                ('for_semsec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmapp.class_section')),
                ('for_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmapp.subject')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pmapp.student')),
            ],
            options={
                'db_table': 'PROJECTS',
            },
        ),
    ]
