# Generated by Django 3.2.9 on 2022-01-31 18:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0005_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='source_url',
        ),
        migrations.CreateModel(
            name='SubmitProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(blank=True, max_length=100, null=True)),
                ('source_url', models.URLField(blank=True, max_length=400, null=True)),
                ('grade', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pmapp.student')),
            ],
            options={
                'db_table': 'SUBMITPROJECT',
            },
        ),
    ]
