# Generated by Django 3.2.9 on 2022-01-31 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0007_remove_project_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitproject',
            name='for_project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pmapp.project'),
        ),
    ]
