# Generated by Django 3.2.9 on 2022-01-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0008_submitproject_for_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='activity_description',
            field=models.TextField(blank=True, help_text='Provide Activity Description(if any)', null=True),
        ),
    ]
