# Generated by Django 3.2.9 on 2022-02-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0009_project_activity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
