# Generated by Django 3.2.9 on 2022-02-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0012_alter_project_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='submisstion_date',
        ),
        migrations.AddField(
            model_name='submitproject',
            name='submisstion_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
