# Generated by Django 3.2.9 on 2022-02-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0013_auto_20220201_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='submitproject',
            name='submisstion_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
